### ISSUE TITLE
This site is wasting my storage through big cookies

### ISSUE THREAD

**Issue by F640** [iptv-org/iptv-org.github.io#4]
I've just noticed that this site has 11 GB cookies from my first visit until now. Maybe like 1 month of frequent visit to this site (https://iptv-org.github.io/). Probably the the logo causing it because when i cleared cookies and loaded a country section (like Afghanistan) with many channels, then 100 MB+ cookies will be used up.

**Comment by freearhey** [comment]
I assume you mean cache, not cookies. But thanks anyway for pointing that out. I will try to reduce its size in the next update.

**Comment by F640** [comment]
> I assume you mean cache, not cookies. But thanks anyway for pointing that out. I will try to reduce its size in the next update.

I mean this:
![IMG_20220508_210749](https://user-images.githubusercontent.com/92260436/167300096-6e3f36b8-9073-4ff2-97ef-308619620f66.jpg)

**Comment by freearhey** [comment]
The thing about cookies is that they can't be bigger than 4Kb in most browsers: https://www.tutorialspoint.com/What-is-the-maximum-size-of-a-web-browser-s-cookies-value

In this case the reason was as you suggested logos that were cached to make the site work in offline mode. I've already updated the code and now the cache size should not exceed 20Mb.

But why the size of the cache is specified in the "Cookie" tab I have no idea.

**Comment by F640** [comment]
> The thing about cookies is that they can't be bigger than 4Kb in most browsers: https://www.tutorialspoint.com/What-is-the-maximum-size-of-a-web-browser-s-cookies-value
> 
> In this case the reason was as you suggested logos that were cached to make the site work in offline mode. I've already updated the code and now the cache size should not exceed 20Mb.
> 
> But why the size of the cache is specified in the "Cookie" tab I have no idea.

I have no idea either. However i don't want to make it work offline, but to make its logo cache removal easier.
